### ISSUE TITLE
OS Ventura Support

### ISSUE THREAD

**Issue by yodaphone** [Dugganclock/Dell-Latitude-5400-Hackintosh-OpenCore#1]
Hi

Were you successful in creating an EFI for Ventura?

**Comment by Dugganclock** [comment]
I have not. I typically stay on the second-to-latest version of MacOS on my computers, for stability and to reduce the need to update as often. I have been taking notes for the future, though and apparently there is a new intel wifi kext necessary for Ventura.

**Comment by yodaphone** [comment]
> I have not. I typically stay on the second-to-latest version of MacOS on my computers, for stability and to reduce the need to update as often. I have been taking notes for the future, though and apparently there is a new intel wifi kext necessary for Ventura. 

Thanks. I tried booting with your EFI but both my nvme drives are not compatible, Micron & a new SKHynix

Got a nvme IO error, gonna try with something else

**Comment by yodaphone** [comment]
i was able to get ventura on the 5400... fully working.. including the trackpoint even though its a bit erratic. thanks to your EFI i had some ideas
